version: "2"
services:
    php:
        container_name: superba_php-fpm
        build: ./docker/php-fpm
        ports:
            - "9000:9001"
        volumes:
            - ./api:/var/www/symfony:cached
            - ./docker/logs/symfony:/var/www/symfony/var/log:cached
        depends_on: 
            - mongodb
        networks:
            - db
            - php

    web:
        image: node:12
        container_name: superba_web
        depends_on:
            - php
        volumes:
            - ./web:/opt/project/
        working_dir: /opt/project
        command: yarn serve --watch
        networks:
            - php
        ports:
            - "3366:8080"
        logging:
            driver: "json-file"
            options:
                max-size: "100MB"
                max-file: "3"

    nginx:
        container_name: superba_nginx
        build: ./docker/nginx
        ports:
            - "80:80"
        depends_on: 
            - php
        networks:
            - php
        volumes:
            - ./docker/logs/nginx:/var/log/nginx:cached
            - ./api:/var/www/symfony:cached

    mongodb:
        image: mongo:4.2.1
        container_name: superba_mongodb
        volumes:
          - mongodb:/data/db/
        ports:
          - "27017:27017"
        networks:
          - db
        logging:
          driver: "json-file"
          options:
            max-size: "100MB"
            max-file: "3"

    dozzle:
        container_name: superba_dozzle
        image: amir20/dozzle:latest
        environment:
        - DOZZLE_TAILSIZE=100
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        ports:
        - "9999:8080"

networks:
    db:
    php:

volumes:
  mongodb: