version: "2"
services:
  api:
    image: node:12
    container_name: superba_api
    depends_on:
      - mongodb
    volumes:
      - ./api:/opt/project/
    working_dir: /opt/project
    command: yarn dev
    networks:
      - backend
      - frontend
    ports:
      - "3355:3355"
      - "9229:9229"
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  web:
    image: node:12
    container_name: superba_web
    depends_on:
      - api
    volumes:
      - ./web:/opt/project/
    working_dir: /opt/project
    command: yarn serve --watch
    networks:
      - frontend
    ports:
      - "3366:3366"
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  nginx:
    image: nginx:stable
    container_name: superba_nginx
    depends_on:
      - web
    networks:
      - frontend
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  mongodb:
    image: mongo:4.2.1
    container_name: superba_mongodb
    volumes:
      - mongodb:/data/db/
    ports:
      - "27017:27017"
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  redis:
    image: redis:5.0.7
    container_name: superba_redis
    networks:
      - backend
    volumes:
      - redis:/data/
    ports:
      - "6379:6379"
    entrypoint: redis-server --appendonly yes
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  dozzle:
    container_name: superba_dozzle
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_TAILSIZE=100
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9999:8080"

networks:
  backend:
  frontend:

volumes:
  mongodb:
  redis:
