version: "3"
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: super_rabbitmq
    networks:
      - backend
      - frontend
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"
  
  mongodb:
    image: mongo:4.2.2
    container_name: super_mongodb
    depends_on: 
      - rabbitmq
    volumes:
      - mongodb:/data/db/
    ports:
      - "27017:27017"
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  api:
    image: node:12
    container_name: super_api
    depends_on:
      - mongodb
    volumes:
      - ./api:/opt/project/
    working_dir: /opt/project
    command: yarn dev
    networks:
      - backend
      - frontend
    ports:
      - "3355:3355"
      - "9229:9229"
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  parser:
    image: node:12
    container_name: super_parser
    depends_on:
      - api
    volumes:
      - ./parser:/opt/project/
    working_dir: /opt/project
    command: yarn dev
    networks:
      - backend
    ports:
      - "9230:9230"
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  web:
    image: node:12
    container_name: super_web
    depends_on:
      - api
    volumes:
      - ./web:/opt/project/
    working_dir: /opt/project
    command: yarn serve --watch
    networks:
      - frontend
    ports:
      - "3366:3366"
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  nginx:
    image: nginx:stable
    container_name: super_nginx
    depends_on:
      - web
    networks:
      - frontend
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"
  
  dozzle:
    container_name: super_dozzle
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_TAILSIZE=100
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9999:8080"

networks:
  default:
  backend:
  frontend:

volumes:
  mongodb:
  redis: