api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

api_oauth_server_auth_login:
    path:  /oauth/v2/auth_login
    defaults: { _controller: ApiBundle:OAuthSecurity:login }

api_oauth_server_auth_login_check:
    path:  /oauth/v2/auth_login_check
    defaults: { _controller: ApiBundle:OAuthSecurity:loginCheck }